rootProject.name = "kotlin-practice"
include("basic")
include("design-pattern")
include("spring-mvc")
include("spring-webflux-security")
include("spring-webflux")
include("spring-webflux-router")
include("algorithm")
include("spring-data-elasticsearch")
include("spring-sns-mysql")
include("spring-armeria-sample")
