# mysql
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - spring-sns-network

volumes:
  mysql:
    driver: local

networks:
  spring-sns-network:
    driver: bridge
