# mysql settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?rewriteBatchedStatements=true&logger=Slf4JLogger&profileSQL=true&maxQuerySizeToLog=999999&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_schema: spring-sns
        jdbc:
          lob:
            non_contextual_creation: true
